name             'planq'
maintainer       'Bolek Tekielski'
maintainer_email 'bt@intraworq.com'
license          'All rights reserved'
description      'Installs and configures PlanQ development environemnt'
long_description 'Installs and configures PlanQ development environemnt'
version          '0.2.0'

depends 'apache2'
depends 'php'
depends 'mysql', '~> 6.0'
depends 'database'
depends 'apt'
#depends 'mysql_chef_gem'